language: python
python:
- '3.3'
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
  sonarqube: true
env:
  global:
  - secure: Oy8W0S88p8jvUDJE3t9Aac/2CI1l+S354eCNqhWhInKhfhOZepPADuQzy5qxfTrs/8DRxy5nylPLFk0nxHzpxHldr9UPBO4b7YYvd66Bi8lY8pmA62vsPjO1m+4u9JQJ3NCHEnttX2fwUU/IPcawNbM7Ne1j2OzJa4TvOF+zI1yHUfWJtmnxt1th8aXwf6GVeeXqPMh970MpTifnjHSxckGwmg5NSY6KoweQ6hBiXeDTMk/jVTWBBoYGZmr6vYjeETsmhzC2VyikQzWasbnjpxqO7A1fkK8j2d4qHF8J2sg3RW2LkGapPd4KzsAS1RvysyrO4cJg77ryUfXTJ7qnViqmxdAGpRyo4sbYMdtv4lcj4wVhLqF6pYSYA0QaRiEkpa2CImhUgu9GRmfHJ8bHFEMIWb6okR1s0r9dJs9fqRj+8KyvidOi/P/rb9/YvA2MwX30U+stpkJQ9WKZ1gb8GC/qh0jN1XDMRuURo174rnAkNJCFthnDOHktk8a9ksYqyQ3omVxOlSb4QRBou9dg/z/Aa/Wr551gb8dilO4Sol+EC6XScBeuCWL9Z035XxEl8O5HflI4LOLOa/ddKETEe5c7NF+DBFNoG7FdZBupDfsUBETe94IrvlThI0zHK+wjC6OgeqqHu93WwYNcrI6Ru+WtDGJk+IxOYUSpPvcZ7vA=
branches:
  only:
  - master
  - Desenvolvimento
install:
- pip install -r requirements.txt
before_script:
- export JAVA_HOME=/usr/lib/jvm/java-8-oracle
script:
- cd wsgi/gde
- python manage.py behave
- cd ..
- cd ..
deploy:
  provider: openshift
  user: projetogde@gmail.com
  password:
    secure: F13foqcBVNTcOS5oNZT2zAdh3Udv72u/G+Dlpqoo6r8fs/7KerYV2ZIRPhveUjpC4qC53ut2ptc/QKbBNWU/iRYsI/xx+EUPj0t8b6emoQe56kF0oyeVVnw0ofu/xT3XKlGzMgOWHtSmz0PaeIxBmz/hQDr2TfnFEF+iuxlMGcpkaE9am5DcF7ECrMOn7Hx7ODWcY+9y8Wi+l5rqZmTU020so+MgixiH+9N3pIVtTbSUQxxa6epeRYgEa1hJ4c5SMH3wzNAzZp1+/2ukUuBgIYNVlq7+meP2U07swKVEye7SGo87bpU/cw57YupJTeXwIe0dKQBo+Z47fLb8py6P+BCelNM50UNWeWVOTvMtaikFEVl5smaeNGTDoX71/GMWbOz2e/t2/gz0NdObb2449mJC4FIJXtQBiEqmuj73qcOsFS8ABc30Twfn/L6nBaSPF2ZssivTisnWZnlqU2pZS6KdSd5euh4d7z9Z+zYbf6Q0zTWH17xMboRs7scSz4i3THVqmudf1tyBfGVOMANXaXmA79QX2IRh33vWqjPuzSsIC/GrelO7W7N5o6UVahi0gsHGpPJrNyhwmgdtgKbBks0xGMx62jEo0v8IpDlZ+aEx52urlhPv4bIZSOU6oDvbM7tvGB7D1Y6CU5Ko+jIRc9U21s8L7iwrgu3A96LxSdo=
  app: gdeifes
  domain: projetogde
  on:
    repo: LEDS/gde
    branch: Desenvolvimento
