language: python
python:
- '3.3'
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
  sonarqube: true
services:
- postgres
#env:
 # global:
  #- secure: vVSzQa1ygJ3gGfB6L1rR43wFWtrjBPWZYdiJetBjHtCQWEKPh7IAc4HK3HcFO1sbPV+poytVdhWY4YhYGquGmDgQl7zMVMoaXPvx8cN3GNzO6bOgTfw4CGmu1r12ZZQB4+FztK9qKH7UEz1xPAizJfKjhhruXFYy8BPyiptZu3zssTM3cexBfhdloeVlfh8rxWoIetVGMkE2k7+l4ioq+tjkmof8x6hN1LBto5kwiOCM4jXTse9OLN9NU9BtY+euz4P9cL9GorDJBzRtvVrHctXu8GTDf4AoXCP2iGgLOF0V5iVjRCNd69I5njG1093S/gEau6IllYie3h/o5mGyPEdxj0EViVslwDZrCDWDj3S01kc2ei+FX7xHZB6BPr2L92CKfwgw93jh+so2WglcROSrh6T2yPPimxUriCrFylZtT90JoeVTZ8rao9Z3IYQXNpUGGKLNslRRyxKTqJwxYbbfYB7L3T4uj0/mc4HZFQtj1sSXcp4t5rHQo+V+oWwexHN/8syM6WAogltOL8cOCXbjCiteYatVsefUAP7zo6qdbRmZkQzu4F5y2Z2keD+Vx/5P0k1/mdyqGeLBkv+MIR6i6dwuJi5Gq19pUm+Wno0RCm8Sl3NjKv+U1Zsex/WFAmC+/KtSNZm4VmHTC7cni63tPVh+Wg25m/QhJa3PNhA=
branches:
  only:
  - master
  - Desenvolvimento
before_install:
- createdb gde
install:
- pip install -r requirements.txt
before_script:
- export JAVA_HOME=/usr/lib/jvm/java-8-oracle
script:
- cd wsgi/gde
- python manage.py makemigrations
- python manage.py migrate
- cd ..
- cd ..
- sonar-scanner -Dsonar.login=$SONAR_TOKEN
deploy:
  provider: openshift
  user: projetogde@gmail.com
  password:
    secure: ch5Ta9MZGyCerKpZGtTwcDC07IhoFi4xpScrqdWegGL5ZyMys49oqnc674FQBotgNsPG5PiiljSTu7yjzQeKUIqoreP7KN5+viQsVAgMUY8/917b+vO/mLSZQTkmEoDZ2LBO3a2HdVUB9xyIfz1xsaI89/BtdqQ0dLMklAo9uLqUBI1CoBs8vmhOaFdc3GrTCJ8DiLOpbMLmQxnPR481ynVnokBu+cc7ngLcIg/TZWJvUGVBvDzX4a1l6BkspUMmBwymHVOdpx1pE97BLBlajuTmtLiQ4qnFDwCkWSZgmQC+NrLiudp0u4flA3VVYRz+rezUj8TOr6l+Rfde949Bvkr1WHbWrakF7QDNihjQe3wthuXpwtUdwv61FUy9Z85IWyHYO9CSlzivUnU52qv29Z4pO4CEONoTgAJEFIU3QwpK2PJmBP90SIE6fk31ZOSbbbIlb9wstWCc4sOeFqCuAVecg2OqaoOD3LmX8Bhyipe8K+icuOhXQ8URuzAKHb6+LBdAh3ZjOHIxF5ETnOBSEjp+Y7OI505B5tPI76APdZ68mWT0wbdVP6ixPHrbvNCT3dKsxzuUdlXiwqncrvKl8/iQsi+ovuM30uJi69heuCbkVvDLOSh5yYPZbK1UI0UATFm4Vggpk17Yu8ml/El00gTATNs2QbQXrrPtZ6r38Fc=
  app: gdeifes
  domain: projetogde
  on:
    repo: LEDS/gde
