dist: trusty
sudo: false
language: python
python:
- '3.3'

jdk:
- oraclejdk8

addons:
  sonarqube:
    organization: "leds-github"
    token:
      secure: "$SONAR_TOKEN"
services:
- postgres

branches:
  only:
  - master
  - Desenvolvimento

before_install:
- createdb gde

install:
- pip install -r requirements.txt

script:
- cd wsgi/gde
- python manage.py makemigrations
- python manage.py migrate
#- python manage.py behave
- cd ..
- cd ..
- sonar-scanner

deploy:
  provider: openshift
  user: projetogde@gmail.com
  password:
    secure: ch5Ta9MZGyCerKpZGtTwcDC07IhoFi4xpScrqdWegGL5ZyMys49oqnc674FQBotgNsPG5PiiljSTu7yjzQeKUIqoreP7KN5+viQsVAgMUY8/917b+vO/mLSZQTkmEoDZ2LBO3a2HdVUB9xyIfz1xsaI89/BtdqQ0dLMklAo9uLqUBI1CoBs8vmhOaFdc3GrTCJ8DiLOpbMLmQxnPR481ynVnokBu+cc7ngLcIg/TZWJvUGVBvDzX4a1l6BkspUMmBwymHVOdpx1pE97BLBlajuTmtLiQ4qnFDwCkWSZgmQC+NrLiudp0u4flA3VVYRz+rezUj8TOr6l+Rfde949Bvkr1WHbWrakF7QDNihjQe3wthuXpwtUdwv61FUy9Z85IWyHYO9CSlzivUnU52qv29Z4pO4CEONoTgAJEFIU3QwpK2PJmBP90SIE6fk31ZOSbbbIlb9wstWCc4sOeFqCuAVecg2OqaoOD3LmX8Bhyipe8K+icuOhXQ8URuzAKHb6+LBdAh3ZjOHIxF5ETnOBSEjp+Y7OI505B5tPI76APdZ68mWT0wbdVP6ixPHrbvNCT3dKsxzuUdlXiwqncrvKl8/iQsi+ovuM30uJi69heuCbkVvDLOSh5yYPZbK1UI0UATFm4Vggpk17Yu8ml/El00gTATNs2QbQXrrPtZ6r38Fc=
  app: gdeifes
  domain: projetogde
  on:
    repo: LEDS/gde
